WIP: main logic (without testing)
alphawolfteam/group-service pull request #1
Opened 2020-12-10 14:58 UTC by yonatandt

Signed-off-by: YonatanTal <yonatald@gmail.com>

2020-12-24 09:35 UTC, ShragaUser commented on src/group/group.repository.ts
> +        $elemMatch: {
$elemMatch is redundant and can be ommited

2020-12-24 13:21 UTC, ShragaUser requested changes
also - reconsider folder tree.
files are speradically placed and dont hold any specific logic.

2020-12-24 13:21 UTC, ShragaUser commented on src/group/group.repository.ts
> +          id: userID,
$elemMatch is redundant and can be ommited

2020-12-24 13:21 UTC, ShragaUser commented on src/group/group.repository.ts
> +    if (!group?.users) {
dont check users

2020-12-24 13:21 UTC, ShragaUser commented on src/group/group.repository.ts
> +    const group = await groupModel
select users

2020-12-24 13:21 UTC, ShragaUser commented on src/group/group.repository.ts
> +import { UserIsNotInGroup } from '../utils/errors/client.error';
not used

2020-12-24 13:21 UTC, ShragaUser commented on src/group/group.model.ts
> +    name: {
index

2020-12-24 13:21 UTC, ShragaUser commented on src/group/group.model.ts
> +      type: [{
user can be its own model -> makes for better validations and adds hooks to user changes. 
better going forward

2020-12-24 13:21 UTC, ShragaUser commented on src/group/group.model.ts
> +        id: { type: String, index: true },
can this be unique index in array?

2020-12-24 13:21 UTC, ShragaUser commented on src/group/group.model.ts
> +      type: String,
validate email

2020-12-24 13:21 UTC, ShragaUser commented on src/group/group.repository.ts
> +  static searchByName(partialName: string): Promise<IGroup[]> {
lowercase? does it matter?

2020-12-24 13:21 UTC, ShragaUser commented on src/group/group.repository.ts
> +  static searchByName(partialName: string): Promise<IGroup[]> {
better to use new RegEx class

2020-12-24 13:21 UTC, ShragaUser commented on src/group/group.repository.ts
> +    return groupModel.findById({ _id: new ObjectID(id) }).exec();
new ObjectID? why? not needed

2020-12-24 13:21 UTC, ShragaUser commented on src/group/group.repository.ts
> +    return groupModel.findByIdAndRemove({ _id: new ObjectID(id) }).exec();
new ObjectID? why? not needed

2020-12-24 13:21 UTC, ShragaUser commented on src/group/group.interface.ts
> +export interface IGroup {
should extend IGroupPrimal

2020-12-24 13:21 UTC, ShragaUser commented on src/group/endpoints/group.endpoint.ts
> +  abstract handler(req: Request, res: Response): Promise<void>;
generally cahnge to be expressHandler

2020-12-24 13:21 UTC, ShragaUser commented on src/group/endpoints/group.create.ts
> +    res.status(201).json(createdGroup);
should return on success

2020-12-24 13:21 UTC, ShragaUser commented on src/index.ts
> +const initializeMongo = async () => {
unsuccesfull connection should kill process

2020-12-24 13:21 UTC, ShragaUser commented on src/index.ts
> +};
should print and kill process with pid 1

2020-12-24 13:21 UTC, ShragaUser commented on src/group/endpoints/group.create.ts
> +    const group: IGroupPrimal = {
should be its own function with its own name

2020-12-24 13:21 UTC, ShragaUser commented on src/group/endpoints/group.searchByName.ts
> +    res.json(groups);
use explicit statuses for response

2020-12-24 13:21 UTC, ShragaUser commented on .gitignore
> +coverage/
more

2020-12-24 13:21 UTC, ShragaUser commented on Dockerfile
> +RUN npm install --production=false --silent
why?

2020-12-24 13:21 UTC, ShragaUser commented on Dockerfile
> +RUN chmod g+rwx -R /usr/src/app
add comment that explains need to use chmod

2020-12-24 13:21 UTC, ShragaUser commented on src/group/endpoints/group.update.ts
> +    partialGroup = pickBy(partialGroup, v => v !== undefined);
name as function with explanation

2020-12-24 13:21 UTC, ShragaUser commented on src/group/endpoints/group.update.ts
> +    partialGroup.modifiedBy = requesterID;
should be handled by handler

2020-12-24 13:21 UTC, ShragaUser commented on src/group/endpoints/group.update.ts
> +      throw new Unexpected(`Unexpected mongoose error while updating group: ${err.message}`);
should be caught by repo if at all

2020-12-24 13:21 UTC, ShragaUser commented on src/group/user/enpoints/group.user.add.ts
> +    return { id: userID, role: userRole };
object should eather be after change / update or return 204 without body

2020-12-24 13:21 UTC, ShragaUser commented on src/group/user/enpoints/group.user.remove.ts
> +    if (!res) {
consider wrapping in function

2020-12-24 13:21 UTC, ShragaUser commented on src/group/user/enpoints/group.user.update.ts
> +    return { id: userID, role: userRole };
object should eather be after change / update or return 204 without body

2020-12-24 13:21 UTC, ShragaUser commented on src/group/group.sharedFunctions.ts
> +  static async verifyUserCanPreformAction(groupID: string, userID: string, requiredRole: UserRole, actionDescription?: string): Promise<void> {
should be verifyUserHasRequiredRole or auto decide requiredRole by getting action as input.

2020-12-24 13:21 UTC, ShragaUser commented on src/group/group.sharedFunctions.ts
> +        `the user has a ${usersRole} role, but needs a ${requiredRole} role${actionMessage}`,
space after 'role'

2020-12-24 13:21 UTC, ShragaUser requested changes
also - reconsider folder tree.
files are speradically placed and dont hold any specific logic.

2020-12-27 10:07 UTC, yonatandt commented on src/group/endpoints/group.create.ts
> +    const group: IGroupPrimal = {
done.
Created an `extractAndTransform` function.

2020-12-27 14:53 UTC, yonatandt commented on src/group/endpoints/group.create.ts
> +    res.status(201).json(createdGroup);
no need to

2020-12-27 16:09 UTC, yonatandt commented on src/group/group.model.ts
> +        id: { type: String, index: true },
It can, but it will also be unique across all the groups, therefore I don't use `unique` here.

2020-12-27 17:03 UTC, yonatandt commented on src/group/group.repository.ts
> +    const group = await groupModel
I don't think it's necessary

2020-12-27 17:07 UTC, yonatandt commented on src/group/group.repository.ts
> +    if (!group?.users) {
I already check `group`, and it's just before accessing the users array. I think it's okay to check the users also just in case.

2020-12-27 17:19 UTC, yonatandt commented on src/group/user/enpoints/group.user.remove.ts
> +    if (!res) {
Did not find a neat way to do that

2020-12-28 11:30 UTC, yonatandt commented on src/group/group.model.ts
> +      type: [{
done.
Created a new file that exports a `userScehma`

2020-12-29 15:04 UTC, ShragaUser approved these changes
LGTM

2021-01-03 12:01 UTC, merged