feat:add icon field to the group.
alphawolfteam/group-service pull request #13
Opened 2021-01-20 18:10 UTC by lustigy96

2021-01-21 06:57 UTC, carmeltsadok requested changes

2021-01-21 06:57 UTC, carmeltsadok commented on src/group/endpoints/group.create.ts
> +        description: Joi.string().required(), // in the group.model this is not requried
Add this message to an issue and remove it from this line

2021-01-21 06:57 UTC, carmeltsadok commented on src/group/group.interface.ts
> +  icon: string;
Because It is not required:
```suggestion
  icon?: string;
```

2021-01-21 13:36 UTC, carmeltsadok commented
Please expand `body-parser` limit in the server so we could send large base64 strings.

2021-02-08 15:15 UTC, carmeltsadok approved these changes

2021-03-03 15:13 UTC, yonatandt approved these changes

2021-03-08 09:20 UTC, merged